module.exports = {
  _id: 0,
  id: 1,
  hash: 1,
  name: 1,
  origin_id: 1,
  destination_id: 1,
  travel_date: 1,
  travel_id: 1,
  route_id: 1,
  description: 1,
  dep_time: 1,
  duration: 1,
  arr_time: 1,
  bus_type: 1,
  cost: 1,
  can_cancel: 1,
  cancellation_time: 1,
  is_service_tax_applicable: 1,
  amenities: 1,
  via: 1,
  cancellation_policy: 1,
  main_dep_time: 1,
  is_ac_bus: 1,
  'bus_layout.total_seats': 1
}
