const express = require('express')
const router = express.Router()
const searchService = require('../services/search')
const bookService = require('../services/booking')
const cancelService = require('../services/cancellations')
const busDetails = require('../middleware/getBus')
const calculateFare = require('../middleware/calculateFare')
const params = require('../serializers/bus')
const validate = require('express-validation')

router.post('/search', validate(params.search), searchService.search)
router.get('/seat', validate(params.seats), searchService.getSeatDetails)
router.post('/book/init', validate(params.initBook), busDetails, calculateFare, bookService.intiBooking)
router.post('/book/validate', validate(params.commitBook), bookService.commitBooking)
router.post('/book/cancel', validate(params.cancel), cancelService.cancel)
module.exports = router
